name: DiscordBot
version: ${project.version}
main: discordbot.discordbot.DiscordBot
authors: [asd]
description: asd
commands:
  verify:
    description: verify player through discord
    usage: /verify <code>