name: DiscordBot
version: ${project.version}
main: discordbot.discordbot.DiscordBot
authors: [asd]
description: asd
commands:
  discordverify:
    description: verify player through discord
    usage: /discordverify <code>